import React from 'react'
import Head from 'next/head'

const Goal = () => {
    return (
        <Head>
            <title>Rick and Morty</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/icon.png" />
        </Head>

    )
}

export default Goal